name: DevSecOps CI Pipeline

on:
  workflow_dispatch:

jobs:
  stage1-Build-docker-Image:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t django-app ./mynotes

      - name: Run Docker Container
        run: docker run -d -p 80:80 --name django-app django-app

      - name: Test Application
        run: |
          sleep 10  # Wait for the container to start
          curl -f http://localhost:80 || exit 1
  
  stage2-Trivy-Scan:
    runs-on: ubuntu-latest
    needs: stage1-Build-docker-Image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image (again for scanning)
        run: docker build -t django-app ./mynotes

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'django-app:latest'
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'