name: DevSecOps CI Pipeline

on:
  workflow_dispatch:

jobs:
  stage1-Build-docker-Image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t django-app ./mynotes

      - name: Run Docker Container
        run: docker run -d -p 80:80 --name django-app django-app

      - name: Test Application
        run: |
          sleep 10  # Wait for the container to start
          curl -f http://localhost:80 || exit 1

  stage2-Trivy-Scan:
    runs-on: ubuntu-latest
    needs: stage1-Build-docker-Image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image (again for scanning)
        run: docker build -t django-app ./mynotes

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'django-app:latest'
          format: 'table'
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  stage3-SonarQube-Scan:
    runs-on: ubuntu-latest
    needs: stage2-Trivy-Scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for PR analysis

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  stage4-notify:
    runs-on: ubuntu-latest
    needs: stage3-SonarQube-Scan
    steps:
      - name: Send workflow status email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: pururajchoudhary2301@gmail.com
          from: ${{ secrets.MAIL_USERNAME }}
          secure: true
          subject: ${{ github.job_status == 'success' && 'Workflow Succeeded' || 'Workflow Failed' }}
          body: ${{ github.job_status == 'success' && 'The workflow completed successfully. Check GitHub Actions for details.' || 'The workflow failed. Check GitHub Actions for details.' }}
